### ISSUE TITLE
Replace hexo theme with something better

### ISSUE THREAD

**Issue by laurenbodnar** [laurenbodnar/laurenbodnar.com#8]
I'm beginning to think the current theme is a bit too minimalistic, and considering other options.

- [x]  Research themes and pick top 5 favorites
- [x] Discuss with @DanielBodnar and get his opinions
- [x] Work with @DanielBodnar to replace current theme with whatever one we agree on

**Comment by danielbodnar** [comment]
Talk about a rabbit trail. In terms of Hexo themes, I think this one is my favorite: https://invom.cc/

**Comment by danielbodnar** [comment]
@laurenbodnar any thoughts on that theme / template?

**Comment by laurenbodnar** [comment]
I LOVE IT!!! I think it has every feature I want and it looks really good out of the box! <3
